trigger:
- dev

pool:
  vmImage: 'Ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    # npm test
     echo "$(Build.SourcesDirectory)"
     echo "$(System.DefaultWorkingDirectory)"
     ls
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: CopyFilesOverSSH@0
   
  displayName: 'Publish artifacts: drop'
  inputs:
          sshEndpoint: 'ubuntu-server'
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: '**'
          targetFolder: '/home/tracy/test'
          readyTimeout: '20000'
          failOnEmptySource: true
          cleanTargetFolder: true

  
